CREATE TABLE IF NOT EXISTS users_table(
    id SERIAL PRIMARY KEY,
    telegram_id BIGINT UNIQUE NOT NULL,
    role VARCHAR(50) NOT NULL,
    balance DOUBLE PRECISION NOT NULL,
    registered_at BIGINT NOT NULL
);